services:
  postgres:
    image: postgres:15
    container_name: car_rental_db
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./car-rental-system-backend
    container_name: car_rental_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_rental_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./car-rental-system-frontend
    container_name: car_rental_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
